# Generated by Django 4.2.4 on 2023-09-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_sem5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
    ]
